# Generated by Django 4.1 on 2022-09-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='long',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
